# ~/.bash_aliases
alias a='git add -A && git commit'
alias b='bundle exec'
alias c='bundle exec rails console'
alias d='bundle exec cap deploy'
alias i='bundle install'
alias la='ls -AlF'
alias ll='ls -lF'
alias p='git push'
alias r='bundle exec rake'
alias s='bundle exec rails server'
alias t='bundle exec rake test'
alias u='sudo aptitude safe-upgrade'
alias w='workspace-status'
